"""
Script for generating versions.h, which will assign the CVS
revision version to each file.
"""
#!/usr/bin/env python2.5

import os
import re
import sys

def readEntriesVersions(filename) :
    """
    Given a CVS/Entries files, this function will return a
    dictionary with the filenames and the CVS revision
    version.
    """
    entries = dict()
    f = open(filename)
    for line in f :
        if re.search("^/",line) :
            foo = re.split("/",line)
            entries[foo[1]] = foo[2]
    f.close()

    return entries

if __name__ == "__main__" :
    filename = os.path.join('CVS','Entries')
    if not os.path.isfile(filename) :
        print "Error: no such file: "+filename
        sys.exit(0)

    entries = readEntriesVersions(filename)

    const = { 'DRAINEH'  : 'draine.h',
              'DRAINEC'  : 'draine.c',
              'SCATTERC' : 'scattercs.c',
              'SCATTERH' : 'scattercs.h' }

    # Create versions.h
    #
    f = open('versions.h','w')
    f.write("// automatically generated by version.py\n")
    for foo in const.keys() :
        f.write("#define "+foo+" "+entries[const[foo]]+"\n")
    
    f.close()
