CDECK  ID>, RDEXP.
      DOUBLE PRECISION FUNCTION RDEXP ( A )
C-----------------------------------------------------------------------
C
C...       FUNCTION RDEXP ( A )                             Ch.Walck    001005
C.
C.    Random number from an exponential distribution with mean A.
C.    This version is using double precsion arithmetics in order 
C.    to avoid the discreteness in the far tail caused by the 24
C.    bit precision of the random numbers generated by RNUNIF as
C.    used in RNEXP. 
C.
C.    F(X;A) = EXP(-X/A) / A
C.
C.    Variable:          X > 0    (real)
C.    Parameter:         A > 0    (real)
C.
C.    Expectation value: E(X) = A
C.    Variance:          V(X) = A**2
C.    Skewness:         G1(X) = 2
C.    Kurtosis:         G2(X) = 6
C.
C.----------------------------------------------------------------------
      DOUBLE PRECISION RNDBLE
      RDEXP = - DBLE(A) * LOG(RNDBLE(A))
      RETURN
      END
